manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 1ee3b93134be23c16ab16b9eb4183bfef63447a6
      import: true

  self:
    path: zephcore
