# Seeed XIAO nRF52840 + Wio-SX1262 (headers)
# SPDX-License-Identifier: MIT

CONFIG_ZEPHCORE_BOARD_NAME="XIAO nRF52840"

CONFIG_BT_DIS_MODEL_NUMBER_STR="Seeed XIAO nRF52840"

CONFIG_ZEPHCORE_SD_FWID=0x0123
